// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJO0pvmHufLdetrxQ8pEGYSxGBFCi9nFA',
    appId: '1:790597821762:web:3ee9f8c55421b5859314db',
    messagingSenderId: '790597821762',
    projectId: 'ulearing-app-eb4b2',
    authDomain: 'ulearing-app-eb4b2.firebaseapp.com',
    storageBucket: 'ulearing-app-eb4b2.appspot.com',
    measurementId: 'G-QE6713YMHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3nkTgehwADkeF13QhpgVOwkk6Jlnwa4E',
    appId: '1:790597821762:android:6ca4865b4e7cf35c9314db',
    messagingSenderId: '790597821762',
    projectId: 'ulearing-app-eb4b2',
    storageBucket: 'ulearing-app-eb4b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfYSlbx92zB8fnDfMthKf5o8jgQELZe74',
    appId: '1:790597821762:ios:ce3ba45532f515029314db',
    messagingSenderId: '790597821762',
    projectId: 'ulearing-app-eb4b2',
    storageBucket: 'ulearing-app-eb4b2.appspot.com',
    iosBundleId: 'com.flutter.ulearning',
  );
}
